spring:
  config:
    activate:
      on-profile: release

  datasource:
    url: jdbc:mysql://retrofy-mysql:3306/retrofy?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8

  flyway:
    url: jdbc:mysql://retrofy-mysql:3306/retrofy