spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/retrofy?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8 # For development
    url: jdbc:mysql://retrofy-mysql:3306/retrofy?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8 # For docker
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  sql:
    init:
      platform: mysql
      mode: always

  flyway:
#    url: jdbc:mysql://retrofy-mysql:3306/retrofy # For development
    url: jdbc:mysql://localhost:3306/retrofy # For docker
    baseline-on-migrate: true
    user: root
    password: ${MYSQL_PASSWORD}
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug
