version: '3.8'

name: retrofy
services:
  app:
    container_name: retrofy-server
    image: 0xcd0/retrofy
    volumes:
      - /retrofy/roms:/retrofy/roms/
    ports:
      - 8080:8080
    restart: always
    environment:
      - MYSQL_PASSWORD=password
    tty: true
    depends_on:
      db:
        condition: service_started
    networks:
      - retrofy-net

  db:
    container_name: retrofy-mysql
    image: mysql:8.1
    volumes:
      - /retrofy/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=retrofy
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - retrofy-net

networks:
  retrofy-net:
    driver: bridge