name: Build retrofy image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        working-directory: ./retrofy
        run: chmod +x gradlew

      - name: ls
        run: ls -al && pwd

      - name: Build Gradle
        working-directory: ./retrofy
        run: ./gradlew bootJar

      - name: ls bootjar
        working-directory: ./retrofy/build/libs
        run: ls -al

      - name: copy ROOT.jar
        working-directory: ./retrofy/build/libs
        run: mv ROOT.jar ./retrofy/docker/server

      - name: ls
        working-directory: ./retrofy/docker/server
        run: ls -al
        

