name: Build retrofy image

on: workflow_dispatch

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v3

      # - name: Grant execute permission for gradlew
      #   working-directory: ./retrofy
      #   run: chmod +x gradlew

      # - name: Build Gradle
      #   working-directory: ./retrofy
      #   run: ./gradlew bootJar
      
      - name: touch
        run: ls -al && pwd && mkdir retrofy/build/ && mkdir retrofy/build/libs
        
      - name: touch
        working-directory: retrofy/build/libs/
        run: touch ROOT.jar

      - name: copy ROOT.jar
        run: pwd && mv retrofy/build/libs/ROOT.jar docker/server && ls -al docker/server       
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./docker/server/
          file: ./docker/server/Dockerfile
          push: true
          tags: 0xcd0/retrofy:latest
        

