name: Build retrofy image

on: workflow_dispatch

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '21'

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v3

      # - name: Grant execute permission for gradlew
      #   working-directory: ./retrofy
      #   run: chmod +x gradlew

      - name: touch
        run: ls -al && pwd && mkdir retrofy/build/ && mkdir retrofy/build/libs
        
      - name: touch
        working-directory: retrofy/build/libs/
        run: touch ROOT.jar

      # - name: Build Gradle
      #   working-directory: ./retrofy
      #   run: ./gradlew bootJar

      - name: ls bootjar
        working-directory: ./retrofy/build/libs
        run: ls -al && pwd

      - name: ls server
        working-directory: docker/server
        run: ls -al && pwd    

      - name: copy ROOT.jar
        run: pwd && mv retrofy/build/libs/ROOT.jar docker/server

      - name: ls
        working-directory: docker/server
        run: ls -al
        

