import { systemListItems } from "interfaces/systemListItems"

export const systems: systemListItems[] = [
    {
        title: "GB / GBC",
        systemName: "gb",
        fullSystemName: "Game Boy / Game Boy Color",
        link: "/game/gb",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "GBA",
        systemName: "gba",
        fullSystemName: "Game Boy Advance",
        link: "/game/gba",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "NES",
        systemName: "nes",
        fullSystemName: "Nintendo Entertainment System",
        link: "/game/nes",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "SNES",
        systemName: "snes",
        fullSystemName: "Super Nintendo Entertainment System",
        link: "/game/snes",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "N64",
        systemName: "n64",
        fullSystemName: "Nintendo 64",
        link: "/game/n64",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "PSX",
        systemName: "psx",
        fullSystemName: "PlayStation",
        link: "/game/psx",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "Sega32X",
        systemName: "sega32x",
        fullSystemName: "Sega 32x",
        link: "/game/sega32x",
        icon: "SportsEsports",
        show: false,
    },
    {
        title: "SegaCD",
        systemName: "segaCD",
        fullSystemName: "Sega CD",
        link: "/game/segacd",
        icon: "SportsEsports",
        show: false,
    },
    {
        title: "SegaGG",
        systemName: "segaGG",
        fullSystemName: "Sega Game Gear",
        link: "/game/segagg",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "SegaMS",
        systemName: "segaMS",
        fullSystemName: "Sega Master System",
        link: "/game/segams",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "SegaMD",
        systemName: "segaMD",
        fullSystemName: "Sega Mega Drive",
        link: "/game/segamd",
        icon: "SportsEsports",
        show: true,
    },
    {
        title: "SegaSaturn",
        systemName: "segaSaturn",
        fullSystemName: "Sega Saturn",
        link: "/game/segasaturn",
        icon: "SportsEsports",
        show: false,
    },
]

export default {
    systems,
}
